"""Initial setup

Revision ID: 9259b2a7c6a8
Revises: 
Create Date: 2025-10-30 13:17:27.144793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9259b2a7c6a8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('Roleid', sa.Integer(), nullable=False),
    sa.Column('Role', sa.String(length=50), nullable=False),
    sa.Column('CreatedBy', sa.String(length=100), nullable=False),
    sa.Column('CreatedDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('ModifiedBy', sa.String(length=100), nullable=True),
    sa.Column('ModifiedDate', sa.DateTime(timezone=True), nullable=True),
    sa.Column('IsDeleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('Roleid'),
    sa.UniqueConstraint('Role')
    )
    op.create_index(op.f('ix_roles_Roleid'), 'roles', ['Roleid'], unique=False)
    op.create_table('station',
    sa.Column('station_id', sa.Integer(), nullable=False),
    sa.Column('station_name', sa.String(length=100), nullable=False),
    sa.Column('station_code', sa.String(length=50), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('station_id'),
    sa.UniqueConstraint('station_code')
    )
    op.create_index(op.f('ix_station_station_id'), 'station', ['station_id'], unique=False)
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('station_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('contact_phone', sa.String(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.Column('modified_by', sa.String(), nullable=True),
    sa.Column('modified_date', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.Roleid'], ),
    sa.ForeignKeyConstraint(['station_id'], ['station.station_id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_station_station_id'), table_name='station')
    op.drop_table('station')
    op.drop_index(op.f('ix_roles_Roleid'), table_name='roles')
    op.drop_table('roles')
    # ### end Alembic commands ###
