"""Added MoCRequest, MoCClosure, and HIRAEntry tables

Revision ID: f84e2d1a5d11
Revises: 9259b2a7c6a8
Create Date: 2025-10-30 14:44:04.554700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f84e2d1a5d11'
down_revision: Union[str, Sequence[str], None] = '9259b2a7c6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menus_MenuId'), table_name='menus')
    op.drop_table('menus')
    op.drop_index(op.f('ix_hira_history_hira_id'), table_name='hira_history')
    op.drop_table('hira_history')
    op.drop_index(op.f('ix_RolePermissions_id'), table_name='RolePermissions')
    op.drop_table('RolePermissions')
    op.drop_index(op.f('ix_moc_closure_history_moc_closure_id'), table_name='moc_closure_history')
    op.drop_index(op.f('ix_moc_closure_history_moc_request_no'), table_name='moc_closure_history')
    op.drop_table('moc_closure_history')
    op.drop_index(op.f('ix_moc_request_history_moc_request_id'), table_name='moc_request_history')
    op.drop_index(op.f('ix_moc_request_history_moc_request_no'), table_name='moc_request_history')
    op.drop_table('moc_request_history')
    op.drop_index(op.f('ix_submenus_SubMenuId'), table_name='submenus')
    op.drop_table('submenus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('submenus',
    sa.Column('SubMenuId', sa.INTEGER(), server_default=sa.text('nextval(\'"submenus_SubMenuId_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('SubMenuName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('SubMenuUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('SubMenuIcon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('MenuId', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['MenuId'], ['menus.MenuId'], name='submenus_MenuId_fkey'),
    sa.PrimaryKeyConstraint('SubMenuId', name='submenus_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_submenus_SubMenuId'), 'submenus', ['SubMenuId'], unique=False)
    op.create_table('moc_request_history',
    sa.Column('moc_request_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('moc_request_no', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('station_name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('priority', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('modification_type', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('time_limit', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('shutdown_required', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('present_system', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('proposed_change', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('justification', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('objectives', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('other_units_impacted', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('statutory_approval_required', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('statutory_approval_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('impact_of_modification', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('consequences_non_implementation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('hse', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('efficiency', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('quality', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('reliability', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('other_aspects', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('objectives_achieved', sa.VARCHAR(length=40), autoincrement=False, nullable=True),
    sa.Column('attachments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('comments', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('moc_request_id', name=op.f('moc_request_history_pkey'))
    )
    op.create_index(op.f('ix_moc_request_history_moc_request_no'), 'moc_request_history', ['moc_request_no'], unique=True)
    op.create_index(op.f('ix_moc_request_history_moc_request_id'), 'moc_request_history', ['moc_request_id'], unique=False)
    op.create_table('moc_closure_history',
    sa.Column('moc_closure_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('moc_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('moc_request_no', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('title_of_moc', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('brief_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('moc_initiator_dept', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('executing_dept', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('moc_execution_details', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('job_start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('job_completion_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('hira_recommendation_status', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('revised_operating_procedure', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('training_completed', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('relevant_manuals', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('comments_initiator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['moc_request_id'], ['moc_requests.moc_request_id'], name=op.f('moc_closure_history_moc_request_id_fkey')),
    sa.PrimaryKeyConstraint('moc_closure_id', name=op.f('moc_closure_history_pkey'))
    )
    op.create_index(op.f('ix_moc_closure_history_moc_request_no'), 'moc_closure_history', ['moc_request_no'], unique=False)
    op.create_index(op.f('ix_moc_closure_history_moc_closure_id'), 'moc_closure_history', ['moc_closure_id'], unique=False)
    op.create_table('RolePermissions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Roleid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('Menuid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SubMenuid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['Menuid'], ['menus.MenuId'], name=op.f('RolePermissions_Menuid_fkey')),
    sa.ForeignKeyConstraint(['Roleid'], ['roles.Roleid'], name=op.f('RolePermissions_Roleid_fkey')),
    sa.ForeignKeyConstraint(['SubMenuid'], ['submenus.SubMenuId'], name=op.f('RolePermissions_SubMenuid_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('RolePermissions_pkey'))
    )
    op.create_index(op.f('ix_RolePermissions_id'), 'RolePermissions', ['id'], unique=False)
    op.create_table('hira_history',
    sa.Column('hira_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('moc_request_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('activity', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('hazard', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('risk_level', postgresql.ENUM('low', 'medium', 'high', 'critical', name='risklevelenum'), autoincrement=False, nullable=False),
    sa.Column('consequence', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('control_measures', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('comments_initiator', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('hira_reviewer_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['moc_request_id'], ['moc_requests.moc_request_id'], name=op.f('hira_history_moc_request_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hira_id', name=op.f('hira_history_pkey'))
    )
    op.create_index(op.f('ix_hira_history_hira_id'), 'hira_history', ['hira_id'], unique=False)
    op.create_table('menus',
    sa.Column('MenuId', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('MenuName', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('MenuUrl', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('MenuIcon', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('MenuId', name=op.f('menus_pkey'))
    )
    op.create_index(op.f('ix_menus_MenuId'), 'menus', ['MenuId'], unique=False)
    # ### end Alembic commands ###
