# app/models/digital_logbook/digital_cp_reading/cp_reading_entry.py
from sqlalchemy import Column, ForeignKey, Integer, String, Date, Time, DateTime
from sqlalchemy.sql import func
from app.database import Base

class CPReadingEntry(Base):
    __tablename__ = "cp_reading_entry"

    cp_entry_id = Column(Integer, primary_key=True, autoincrement=True)
    master_id = Column(Integer, ForeignKey("cp_reading_master.cp_master_id", ondelete="CASCADE"), nullable=False, index=True)

    sr_no = Column(Integer, nullable=True)
    entry_date = Column(Date, nullable=True)
    entry_time = Column(Time, nullable=True)
    remarks = Column(String(255), nullable=True)

    # Station 1: MLR
    mlr_ac_ip_v = Column(String(20), nullable=True)
    mlr_psp_ve = Column(String(20), nullable=True)
    mlr_ac_ip_amp = Column(String(20), nullable=True)
    mlr_op_dc_v = Column(String(20), nullable=True)
    mlr_op_dc_amp = Column(String(20), nullable=True)
    sv1_ac_ip_v = Column(String(20), nullable=True)
    sv1_psp_ve = Column(String(20), nullable=True)
    sv1_ac_ip_amp = Column(String(20), nullable=True)
    sv1_op_dc_v = Column(String(20), nullable=True)
    sv1_op_dc_amp = Column(String(20), nullable=True)
    sv2_ac_ip_v = Column(String(20), nullable=True)
    sv2_psp_ve = Column(String(20), nullable=True)
    sv2_ac_ip_amp = Column(String(20), nullable=True)
    sv2_op_dc_v = Column(String(20), nullable=True)
    sv2_op_dc_amp = Column(String(20), nullable=True)

    # Station 2: NER
    ner_ac_ip_v = Column(String(20), nullable=True)
    ner_psp_ve = Column(String(20), nullable=True)
    ner_ac_ip_amp = Column(String(20), nullable=True)
    ner_op_dc_v = Column(String(20), nullable=True)
    ner_op_dc_amp = Column(String(20), nullable=True)
    sv3_ac_ip_v = Column(String(20), nullable=True)
    sv3_psp_ve = Column(String(20), nullable=True)
    sv3_ac_ip_amp = Column(String(20), nullable=True)
    sv3_op_dc_v = Column(String(20), nullable=True)
    sv3_op_dc_amp = Column(String(20), nullable=True)
    sv4_ac_ip_v = Column(String(20), nullable=True)
    sv4_psp_ve = Column(String(20), nullable=True)
    sv4_ac_ip_amp = Column(String(20), nullable=True)
    sv4_op_dc_v = Column(String(20), nullable=True)
    sv4_op_dc_amp = Column(String(20), nullable=True)

    # Station 3: HSN
    hsn_ac_ip_v = Column(String(20), nullable=True)
    hsn_psp_ve = Column(String(20), nullable=True)
    hsn_ac_ip_amp = Column(String(20), nullable=True)
    hsn_op_dc_v = Column(String(20), nullable=True)
    hsn_op_dc_amp = Column(String(20), nullable=True)
    sv5_ac_ip_v = Column(String(20), nullable=True)
    sv5_psp_ve = Column(String(20), nullable=True)
    sv5_ac_ip_amp = Column(String(20), nullable=True)
    sv5_op_dc_v = Column(String(20), nullable=True)
    sv5_op_dc_amp = Column(String(20), nullable=True)
    sv6_ac_ip_v = Column(String(20), nullable=True)
    sv6_psp_ve = Column(String(20), nullable=True)
    sv6_ac_ip_amp = Column(String(20), nullable=True)
    sv6_op_dc_v = Column(String(20), nullable=True)
    sv6_op_dc_amp = Column(String(20), nullable=True)
    sv7_ac_ip_v = Column(String(20), nullable=True)
    sv7_psp_ve = Column(String(20), nullable=True)
    sv7_ac_ip_amp = Column(String(20), nullable=True)
    sv7_op_dc_v = Column(String(20), nullable=True)
    sv7_op_dc_amp = Column(String(20), nullable=True)

    # Station 4: DKN
    dkn_ac_ip_v = Column(String(20), nullable=True)
    dkn_psp_ve = Column(String(20), nullable=True)
    dkn_ac_ip_amp = Column(String(20), nullable=True)
    dkn_op_dc_v = Column(String(20), nullable=True)
    dkn_op_dc_amp = Column(String(20), nullable=True)
    sv8_ac_ip_v = Column(String(20), nullable=True)
    sv8_psp_ve = Column(String(20), nullable=True)
    sv8_ac_ip_amp = Column(String(20), nullable=True)
    sv8_op_dc_v = Column(String(20), nullable=True)
    sv8_op_dc_amp = Column(String(20), nullable=True)
    ipstn_ac_ip_v = Column(String(20), nullable=True)
    ipstn_psp_ve = Column(String(20), nullable=True)
    ipstn_ac_ip_amp = Column(String(20), nullable=True)
    ipstn_op_dc_v = Column(String(20), nullable=True)
    ipstn_op_dc_amp = Column(String(20), nullable=True)
    sv9_ac_ip_v = Column(String(20), nullable=True)
    sv9_psp_ve = Column(String(20), nullable=True)
    sv9_ac_ip_amp = Column(String(20), nullable=True)
    sv9_op_dc_v = Column(String(20), nullable=True)
    sv9_op_dc_amp = Column(String(20), nullable=True)
    sv10_ac_ip_v = Column(String(20), nullable=True)
    sv10_psp_ve = Column(String(20), nullable=True)
    sv10_ac_ip_amp = Column(String(20), nullable=True)
    sv10_op_dc_v = Column(String(20), nullable=True)
    sv10_op_dc_amp = Column(String(20), nullable=True)

    created_at = Column(DateTime, server_default=func.now(), nullable=True)
    created_by = Column(Integer, nullable=True)
    updated_at = Column(DateTime, nullable=True)
    updated_by = Column(Integer, nullable=True)
