# ==================================================
# Monthly Leave Allocation Cron — FIXED v3
# ==================================================
# ALL BUGS FIXED:
#
#   BUG 1: _current_el_balance — NOT IN with wildcards never filters
#           BROKEN:  NOT IN ('%rejected%', '%cancelled%')
#           FIXED:   NOT LIKE '%rejected%' AND NOT LIKE '%cancelled%'
#
#   BUG 2 & 3: leave_year is a GENERATED column — cannot INSERT into it
#           FIXED:   removed leave_year from all INSERT statements
#
#   BUG 4: create_leave_encashment — balance_as_on_date was set to
#           opening balance instead of remaining after encashment
#           FIXED:   remain = balance - encash_qty
#
#   BUG 5: process_el_allocation — silently returned when opening < 292
#           even though projected >= 292 (no allocation happened at all)
#           FIXED:   falls back to capped normal allocation
#
#   BUG 6: ON CONFLICT DO NOTHING blocks force=True inserts for EL_NE=0
#           Unique constraint (user_id, type_id, leave_year) means
#           force insert with qty=0 is silently skipped — row missing
#           FIXED:   force=True uses DO UPDATE SET to guarantee the write
# ==================================================
#
# BEFORE RUNNING — RESET OLD BUGGY DATA:
#
#   -- Delete bad Q1 2026 EL rows created by old cron (all users)
#   DELETE FROM leave_balances
#   WHERE type_id IN (
#       SELECT type_id FROM leave_types WHERE code IN ('EL_E', 'EL_NE')
#   )
#   AND leave_year = 2026
#   AND DATE_PART('quarter', created_date) = 1;
#
#   -- Fix user 462 permanent_from for testing
#   UPDATE users SET permanent_from = '2020-01-01' WHERE user_id = 462;
#
# ==================================================

from datetime import date, datetime
import math
import traceback

from sqlalchemy import text
from sqlalchemy.orm import Session


# ==================================================
# CONSTANTS
# ==================================================

CL_BY_MONTH = {
    1: 10, 2: 9,  3: 8,  4: 8,  5: 7,  6: 6,
    7: 5,  8: 4,  9: 3,  10: 3, 11: 2, 12: 1
}

HPL_BY_MONTH = {
    1: 20, 2: 18, 3: 17, 4: 15, 5: 13, 6: 12,
    7: 10, 8: 8,  9: 7,  10: 5, 11: 3, 12: 2
}

MAX_EL         = 300
STATUS_PENDING = "Approval Pending"

EL_HARDCODED_TABLE = {
    292: {"enc": 6, "non": 2, "encash": 0},
    293: {"enc": 5, "non": 2, "encash": 1},
    294: {"enc": 5, "non": 1, "encash": 2},
    295: {"enc": 4, "non": 1, "encash": 3},
    296: {"enc": 3, "non": 1, "encash": 4},
    297: {"enc": 2, "non": 1, "encash": 5},
    298: {"enc": 2, "non": 0, "encash": 6},
    299: {"enc": 1, "non": 0, "encash": 7},
    300: {"enc": 0, "non": 0, "encash": 8},
}


# ==================================================
# DATE HELPERS
# ==================================================

def current_quarter(today: date) -> int:
    return (today.month - 1) // 3 + 1


def calculate_el_for_quarter(q_month_idx: int):
    eligible_months = {1: 3, 2: 2, 3: 1}[q_month_idx]
    enc = int(6 * eligible_months / 3)
    non = math.ceil(2 * eligible_months / 3) if eligible_months > 0 else 0
    return enc, non, enc + non


def effective_start_month(user, current_year):
    doj  = user.get("date_of_joining")
    perm = user.get("permanent_from")
    if not doj and not perm:
        return None, None
    # Use permanent_from if available (DOJ can be a future re-join date)
    start = perm if perm else doj
    return start.year, start.month


# ==================================================
# DB HELPERS
# ==================================================

def auto_confirm_employees(db):
    """Convert probation → permanent once probation_to is crossed."""
    db.execute(text("""
        UPDATE users
        SET employment_type = 'Permanent',
            permanent_from  = probation_to
        WHERE employment_type = 'Probation'
          AND probation_to IS NOT NULL
          AND probation_to <= CURRENT_DATE
    """))
    print("✅ auto_confirm_employees done")


def _insert_rh_balance(db, user_id, type_id, qty):
    """
    Insert RH balance.
    leave_year is GENERATED by Postgres from created_date — do NOT insert it.
    """
    db.execute(text("""
        INSERT INTO leave_balances
            (user_id, type_id, allocated, used, balance, is_usable, created_date)
        VALUES
            (:uid, :tid, :qty, 0, :qty, FALSE, NOW())
        ON CONFLICT ON CONSTRAINT uniq_leave_year_type
        DO NOTHING
    """), {"uid": user_id, "tid": type_id, "qty": qty})


def _insert_balance(db, user_id, type_id, qty, force=False):
    """
    Insert leave balance row.

    leave_year is GENERATED — never insert it.
    Postgres auto-computes it from created_date.

    force=True → use DO UPDATE so qty=0 rows are always written.
    (DO NOTHING would silently skip on conflict — BUG 6 FIX)

    force=False → use DO NOTHING (safe idempotent re-run).
    """
    if qty <= 0 and not force:
        return

    try:
        if force:
            # BUG 6 FIX: DO UPDATE guarantees the row is always written
            db.execute(text("""
                INSERT INTO leave_balances
                    (user_id, type_id, allocated, used, balance, is_usable, created_date)
                VALUES
                    (:uid, :tid, :qty, 0, :qty, TRUE, NOW())
                ON CONFLICT ON CONSTRAINT uniq_leave_year_type
                DO UPDATE SET
                    allocated    = EXCLUDED.allocated,
                    balance      = EXCLUDED.balance,
                    is_usable    = EXCLUDED.is_usable,
                    created_date = EXCLUDED.created_date
            """), {"uid": user_id, "tid": type_id, "qty": qty})
        else:
            db.execute(text("""
                INSERT INTO leave_balances
                    (user_id, type_id, allocated, used, balance, is_usable, created_date)
                VALUES
                    (:uid, :tid, :qty, 0, :qty, TRUE, NOW())
                ON CONFLICT ON CONSTRAINT uniq_leave_year_type
                DO NOTHING
            """), {"uid": user_id, "tid": type_id, "qty": qty})

    except Exception:
        print(f"❌ ERROR inserting leave balance user={user_id} type={type_id} qty={qty}")
        print(traceback.format_exc())
        raise


def deduct_el_fifo(db, user_id, qty, EL_E, EL_NE):
    """Deduct EL from existing balances using FIFO (oldest first)."""
    rows = db.execute(text("""
        SELECT balance_id, balance
        FROM leave_balances
        WHERE user_id  = :uid
          AND type_id IN (:enc, :non)
          AND balance  > 0
        ORDER BY created_date
    """), {"uid": user_id, "enc": EL_E, "non": EL_NE}).fetchall()

    remaining = qty
    for r in rows:
        if remaining <= 0:
            break
        consume = min(r[1], remaining)
        db.execute(text("""
            UPDATE leave_balances
            SET used    = used    + :q,
                balance = balance - :q
            WHERE balance_id = :bid
        """), {"q": consume, "bid": r[0]})
        remaining -= consume


# ==================================================
# EL BALANCE — AUTHORITATIVE
# ==================================================

def _current_el_balance(db, user_id, EL_E, EL_NE) -> int:
    """
    Opening EL = Total Allocated - Used (approved leaves) - Encashed

    BUG 1 FIX: was NOT IN ('%rejected%', '%cancelled%')
    NOT IN does exact string match — wildcards are ignored.
    Fixed to use NOT LIKE.
    """
    alloc = db.execute(text("""
        SELECT COALESCE(SUM(allocated), 0)
        FROM leave_balances
        WHERE user_id  = :uid
          AND type_id IN (:enc, :non)
    """), {"uid": user_id, "enc": EL_E, "non": EL_NE}).scalar() or 0

    used = db.execute(text("""
        SELECT COALESCE(SUM(number_of_days), 0)
        FROM hr_leave_application
        WHERE user_id    = :uid
          AND leave_type = 'EL'
          AND LOWER(status) IN ('approved', 'reversal approved', 'withdraw rejected')
    """), {"uid": user_id}).scalar() or 0

    # BUG 1 FIX: NOT IN with wildcards → use NOT LIKE
    encashed = db.execute(text("""
        SELECT COALESCE(SUM(le.encash_el), 0)
        FROM leave_encashment le
        LEFT JOIN encashment_main em
               ON em.encashment_main_id = le.encashment_main_id
        WHERE LOWER(le.status) NOT LIKE '%rejected%'
          AND LOWER(le.status) NOT LIKE '%cancelled%'
          AND (le.created_by = :uid OR em.created_by = :uid)
    """), {"uid": user_id}).scalar() or 0

    balance = max(int(alloc - used - encashed), 0)
    print(f"    [EL BALANCE] user={user_id} alloc={alloc} used={used} encashed={encashed} → {balance}")
    return balance


# ==================================================
# USER LOOKUP
# ==================================================

def get_user_by_id(db, user_id):
    if isinstance(user_id, dict):
        user_id = user_id.get("user_id")
    if hasattr(user_id, "_mapping"):
        user_id = user_id["user_id"]
    user_id = int(user_id)

    return db.execute(text("""
        SELECT
            u.user_id,
            CONCAT(u.first_name, ' ', u.last_name) AS employee_name,
            u.employee_code,
            u.designation,
            u.station
        FROM users u
        WHERE u.user_id = :uid
    """), {"uid": user_id}).mappings().first()


# ==================================================
# ENCASHMENT
# ==================================================

def generate_encashment_ref(db: Session) -> str:
    year   = datetime.now().year
    prefix = f"ENC/{year}/"

    last = db.execute(text("""
        SELECT encashment_ref_id
        FROM encashment_main
        WHERE encashment_ref_id LIKE :prefix
        ORDER BY encashment_main_id DESC
        LIMIT 1
    """), {"prefix": f"{prefix}%"}).scalar()

    next_no = 1
    if last:
        try:
            next_no = int(last.split("/")[-1]) + 1
        except ValueError:
            next_no = 1

    return f"{prefix}{str(next_no).zfill(6)}"


def create_encashment_main(db, user_id) -> int:
    user    = get_user_by_id(db, user_id)
    enc_ref = generate_encashment_ref(db)

    print(f"    [ENCASHMENT MAIN] user={user_id} ref={enc_ref}")

    mid = db.execute(text("""
        INSERT INTO encashment_main (
            encashment_ref_id, employee_name, employee_code,
            designation, station, claim_module, status, created_by
        ) VALUES (
            :ref, :name, :code, :desg, :station,
            'Leave Encashment', :status, :by
        )
        RETURNING encashment_main_id
    """), {
        "ref":     enc_ref,
        "name":    user["employee_name"],
        "code":    user["employee_code"],
        "desg":    user["designation"],
        "station": user["station"],
        "status":  STATUS_PENDING,
        "by":      user["user_id"],
    }).scalar()

    print(f"    [ENCASHMENT MAIN] Created id={mid}")
    return mid


def create_leave_encashment(db, mid, user_id, encash_qty, balance):
    """
    BUG 4 FIX: balance_as_on_date was the opening balance.
    It should be the REMAINING balance after encashment.
    """
    user      = get_user_by_id(db, user_id)
    remaining = balance - encash_qty   # BUG 4 FIX

    print(f"    [LEAVE ENCASHMENT] user={user_id} opening={balance} encash={encash_qty} remaining={remaining}")

    db.execute(text("""
        INSERT INTO leave_encashment (
            encashment_main_id, employee_name, employee_code,
            designation, station, encashment_date, leave_type,
            el_encashable, encash_el, balance_as_on_date, status, created_by
        ) VALUES (
            :mid, :name, :code, :desg, :station,
            :dt, 'EL', :bal, :encash, :remain, :status, :by
        )
    """), {
        "mid":     mid,
        "name":    user["employee_name"],
        "code":    user["employee_code"],
        "desg":    user["designation"],
        "station": user["station"],
        "dt":      date.today(),
        "bal":     balance,
        "encash":  encash_qty,
        "remain":  remaining,      # BUG 4 FIX
        "status":  STATUS_PENDING,
        "by":      user["user_id"],
    })


# ==================================================
# EL ALLOCATION WITH ENCASHMENT
# ==================================================

def process_el_allocation(db, user, current, enc, non, EL_E, EL_NE):
    """
    Called when projected EL >= 292.

    BUG 5 FIX: old code did `if opening < 292: return` — nothing happened
    when current was e.g. 290 but projected was 298.
    Now falls back to a headroom-capped normal insert.

    BUG 6 FIX: force inserts use DO UPDATE so qty=0 rows are always written.
    """
    opening = min(current, MAX_EL)

    print(f"  [PROCESS EL] user={user['user_id']} current={current} opening={opening}")

    # BUG 5 FIX: was `if opening < 292: return`
    if opening < 292:
        headroom = MAX_EL - current
        safe_enc = min(enc, headroom)
        safe_non = min(non, max(headroom - safe_enc, 0))
        print(f"  [PROCESS EL] opening<292 fallback enc={safe_enc} non={safe_non}")
        _insert_balance(db, user["user_id"], EL_E,  safe_enc)
        _insert_balance(db, user["user_id"], EL_NE, safe_non)
        return

    row             = EL_HARDCODED_TABLE[opening]
    enc_to_allocate = row["enc"]
    non_to_allocate = row["non"]
    auto_encash     = row["encash"]

    print(f"  [PROCESS EL] table[{opening}] → enc={enc_to_allocate} non={non_to_allocate} encash={auto_encash}")

    # BUG 6 FIX: force=True + DO UPDATE guarantees these rows are written
    _insert_balance(db, user["user_id"], EL_E,  enc_to_allocate, force=True)
    _insert_balance(db, user["user_id"], EL_NE, non_to_allocate, force=True)

    # Encashment created only when opening > 292 (292 row has encash=0)
    if opening > 292:
        mid = create_encashment_main(db, user["user_id"])
        create_leave_encashment(
            db=db,
            mid=mid,
            user_id=user["user_id"],
            encash_qty=auto_encash,
            balance=current,
        )

    final_balance = opening + enc_to_allocate + non_to_allocate
    assert final_balance == MAX_EL, \
        f"❌ EL cap mismatch user={user['user_id']}: {final_balance} != {MAX_EL}"
    print(f"  [PROCESS EL] ✅ final balance = {final_balance}")


# ==================================================
# MAIN CRON
# ==================================================

def run_monthly_leave_cron(db):

    today   = date.today()
    year    = today.year
    quarter = current_quarter(today)

    print(f"\n{'='*60}")
    print(f"LEAVE CRON | {today} | Year={year} | Q{quarter}")
    print(f"{'='*60}\n")

    # ── Step 1: Auto-confirm probation employees ──────────────
    auto_confirm_employees(db)

    # ── Step 2: Load users ────────────────────────────────────
    users = db.execute(text("""
        SELECT user_id,
               employment_type,
               date_of_joining,
               probation_from,
               probation_to,
               permanent_from
        FROM users
        WHERE employment_type IN ('Permanent', 'Probation')
          AND is_deleted = FALSE
    """)).mappings().all()

    print(f"Loaded {len(users)} users\n")

    # ── Step 3: Load leave type IDs ───────────────────────────
    leave_types = {
        r.code: r.type_id
        for r in db.execute(text("SELECT type_id, code FROM leave_types"))
    }

    CL    = leave_types["CL"]
    HPL   = leave_types["HPL"]
    EL_E  = leave_types["EL_E"]
    EL_NE = leave_types["EL_NE"]
    RH    = leave_types["RH"]

    print(f"Leave types → CL={CL} HPL={HPL} EL_E={EL_E} EL_NE={EL_NE} RH={RH}\n")

    # ==================================================
    # ANNUAL LEAVES (CL + HPL + RH)
    # ==================================================

    print("── ANNUAL LEAVES ──────────────────────────────────────")

    for u in users:
        uid = u["user_id"]

        # ── RH: 2 per year for everyone ───────────────────────
        rh_exists = db.execute(text("""
            SELECT 1 FROM leave_balances
            WHERE user_id   = :uid
              AND type_id   = :rh
              AND leave_year = :yr
        """), {"uid": uid, "rh": RH, "yr": year}).first()

        if not rh_exists:
            _insert_rh_balance(db, uid, RH, 2)
            print(f"  RH | user={uid} qty=2")

        # ── PROBATION → CL only ───────────────────────────────
        if u["employment_type"] == "Probation":
            cl_exists = db.execute(text("""
                SELECT 1 FROM leave_balances
                WHERE user_id   = :uid
                  AND type_id   = :cl
                  AND leave_year = :yr
            """), {"uid": uid, "cl": CL, "yr": year}).first()

            if cl_exists:
                continue

            elig_date = u.get("probation_from") or u.get("date_of_joining")
            if not elig_date:
                continue

            cl_qty = CL_BY_MONTH[1] if elig_date.year < year \
                     else CL_BY_MONTH[elig_date.month]
            _insert_balance(db, uid, CL, cl_qty)
            print(f"  CL | user={uid} qty={cl_qty} [Probation]")

        # ── PERMANENT → CL + HPL ──────────────────────────────
        elif u["employment_type"] == "Permanent":
            start_year, start_month = effective_start_month(u, year)
            if not start_year:
                print(f"  SKIP annual | user={uid} — missing DOJ/permanent_from")
                continue

            if start_year < year:
                cl_qty, hpl_qty = CL_BY_MONTH[1], HPL_BY_MONTH[1]
            elif start_year == year:
                cl_qty, hpl_qty = CL_BY_MONTH[start_month], HPL_BY_MONTH[start_month]
            else:
                print(f"  SKIP annual | user={uid} — starts future year {start_year}")
                continue

            cl_exists = db.execute(text("""
                SELECT 1 FROM leave_balances
                WHERE user_id   = :uid
                  AND type_id   = :cl
                  AND leave_year = :yr
            """), {"uid": uid, "cl": CL, "yr": year}).first()

            if not cl_exists:
                _insert_balance(db, uid, CL, cl_qty)
                print(f"  CL | user={uid} qty={cl_qty} [Permanent]")

            hpl_exists = db.execute(text("""
                SELECT 1 FROM leave_balances
                WHERE user_id   = :uid
                  AND type_id   = :hpl
                  AND leave_year = :yr
            """), {"uid": uid, "hpl": HPL, "yr": year}).first()

            if not hpl_exists:
                _insert_balance(db, uid, HPL, hpl_qty)
                print(f"  HPL | user={uid} qty={hpl_qty} [Permanent]")

    # ==================================================
    # QUARTERLY EL (Permanent only)
    # ==================================================

    print("\n── QUARTERLY EL ───────────────────────────────────────")

    for u in users:
        if u["employment_type"] != "Permanent":
            continue

        uid = u["user_id"]

        # ── Already allocated this quarter? ───────────────────
        el_exists = db.execute(text("""
            SELECT 1 FROM leave_balances
            WHERE user_id   = :uid
              AND type_id  IN (:el_e, :el_ne)
              AND leave_year = :yr
              AND DATE_PART('quarter', created_date) = :qr
        """), {
            "uid": uid, "el_e": EL_E, "el_ne": EL_NE,
            "yr": year, "qr": quarter,
        }).first()

        if el_exists:
            print(f"  SKIP EL | user={uid} — already allocated Q{quarter} {year}")
            continue

        # ── Eligibility ───────────────────────────────────────
        # EL eligibility is based on permanent_from (when they became permanent).
        # DOJ is only a fallback if permanent_from is missing.
        # NEVER use max(DOJ, permanent_from) — DOJ can be a future date
        # and would incorrectly override permanent_from.
        doj  = u.get("date_of_joining")
        perm = u.get("permanent_from")

        if not perm and not doj:
            print(f"  SKIP EL | user={uid} — no permanent_from and no DOJ")
            continue

        # Use permanent_from if available, else fall back to DOJ
        elig   = perm if perm else doj
        elig_q = ((elig.month - 1) // 3) + 1

        if elig.year > year or (elig.year == year and elig_q > quarter):
            print(f"  SKIP EL | user={uid} — not eligible yet (elig={elig} Q{elig_q})")
            continue

        # ── Quarter month index ───────────────────────────────
        q_month_idx = 1 if (elig.year < year or elig_q < quarter) \
                      else ((elig.month - 1) % 3) + 1

        enc, non, total_new = calculate_el_for_quarter(q_month_idx)
        current             = _current_el_balance(db, uid, EL_E, EL_NE)
        projected           = current + total_new

        print(f"  EL | user={uid} current={current} +{total_new} projected={projected} q_idx={q_month_idx}")

        # ── Cap logic ─────────────────────────────────────────
        if projected >= 292:
            process_el_allocation(
                db=db, user=u, current=current,
                enc=enc, non=non, EL_E=EL_E, EL_NE=EL_NE,
            )
        else:
            _insert_balance(db, uid, EL_E,  enc)
            _insert_balance(db, uid, EL_NE, non)
            print(f"  EL allocated | user={uid} EL_E={enc} EL_NE={non}")

        # ── Safety guard ──────────────────────────────────────
        final = _current_el_balance(db, uid, EL_E, EL_NE)
        assert final <= MAX_EL, \
            f"❌ EL exceeded cap! user={uid} balance={final}"

    # ==================================================
    # Disable previous-year CL
    # ==================================================

    print("\n── DISABLING OLD CL ───────────────────────────────────")
    db.execute(text("""
        UPDATE leave_balances
        SET is_usable = FALSE
        WHERE type_id   = :cl
          AND leave_year < :yr
    """), {"cl": CL, "yr": year})

    db.commit()
    print("\n✅ Monthly leave cron completed successfully.")